In [105]:
import pandas as pd, numpy as np

pred = pd.read_csv("./submission.csv")
pred.head()

      session_type                                             labels
0  12899779_clicks  59625 1253524 737445 438191 731692 1790770 942...
1  12899780_clicks  1142000 736515 973453 582732 1502122 889686 17...
2  12899781_clicks  918667 199008 194067 57315 141736 1460571 7594...
3  12899782_clicks  834354 595994 740494 889671 987399 779477 1344...
4  12899783_clicks  1817895 607638 1754419 1216820 1729553 300127 ...

In [106]:
split_data  = pred["session_type"].str.split("_", expand=True)

In [107]:
split_data.columns = ["session", "type"]
pred[["session", "type"]] = split_data

In [108]:
pred.drop("session_type", axis=1, inplace=True)
pred["session"] = pred["session"].astype(int)

In [109]:
pred.sort_values("session", inplace=True)
session_max = int(pred["session"].max())
session_min = int(pred["session"].min())

In [128]:
# 随机抽取10个人查看 
random_index = set(np.random.randint(session_min, session_max, 10))
cond_index = ((pred["session"].isin(random_index)) & (pred["type"] != "carts"))

In [129]:
# 使用布尔索引截取
selected = pred[cond_index]
selected.reset_index(drop=True, inplace=True)

In [130]:
selected.head()

                                               labels   session    type
0   1833983 1197632 1796103 226413 1492411 620545 ...  12931542  orders
1   1833983 1197632 1796103 226413 620545 1492411 ...  12931542  clicks
2   1685214 1531805 1798916 1208112 620813 1833893...  13064076  clicks
3   1685214 1531805 1798916 1208112 620813 1833893...  13064076  orders
4   221749 1595183 212264 1370557 885193 512326 54...  13102811  clicks
5   221749 1595183 212264 433413 885193 1178678 16...  13102811  orders
6   723768 631899 1358447 838455 1400630 695107 59...  13308611  clicks
7   723768 631899 838455 1400630 695107 597939 635...  13308611  orders
8   1296980 1013091 292791 1632953 1599316 1230612...  13697432  orders
9   1296980 1013091 292791 1632953 1599316 1409901...  13697432  clicks
10  1292042 383364 1734305 1043508 986164 390163 2...  13786912  clicks
11  1292042 383364 1734305 1043508 986164 634452 2...  13786912  orders
12  1420240 208189 507852 7793 897199 1494678 1007...  14119775  orders
13  1420240 208189 7793 1007548 897199 1566944 881...  14119775  clicks
14  1792575 687129 274754 666755 312131 997205 689...  14160166  orders
15  1792575 687129 274754 666755 312131 997205 689...  14160166  clicks
16  879210 749658 967550 1595450 1391327 216753 52...  14487141  orders
17  879210 749658 967550 1595450 840775 1457619 17...  14487141  clicks
18  954118 1510044 274967 456331 66284 389023 3125...  14560351  orders
19  954118 1510044 274967 456331 823143 66284 1171...  14560351  clicks

In [151]:
for session in set(selected.session):
    row = selected[selected["session"] == session]
    clicks = row[row["type"] == "clicks"]
    orders = row[row["type"] == "orders"]
    print(f"Session号为{session}的用户：")
    print(f"    可能点击的商品序列为：{np.array(clicks["labels"])}")
    print(f"    可能购买的商品序列为：{np.array(orders["labels"])}")
    print(f"\n")

Session号为13786912的用户：
    可能点击的商品序列为：['1292042 383364 1734305 1043508 986164 390163 274783 634452 881286 647522 1679224 423037 147526 688602 130020 1723428 1596300 1811963 508883 785712']
    可能购买的商品序列为：['1292042 383364 1734305 1043508 986164 634452 274783 881286 390163 423037 130020 688602 1723428 1596300 647522 727928 147526 752756 474743 1200295']


Session号为13308611的用户：
    可能点击的商品序列为：['723768 631899 1358447 838455 1400630 695107 597939 1667586 63531 672318 351055 1368396 28759 1845894 127805 621731 1566017 516765 127183 11771']
    可能购买的商品序列为：['723768 631899 838455 1400630 695107 597939 63531 672318 351055 1358447 621731 11771 1667586 1623390 1368396 127183 270632 28759 565341 127805']


Session号为14487141的用户：
    可能点击的商品序列为：['879210 749658 967550 1595450 840775 1457619 1722108 41854 168636 1658205 1821845 284631 686934 1391327 805670 1444626 1687172 216753 1762252 1554359']
    可能购买的商品序列为：['879210 749658 967550 1595450 1391327 216753 52039 840775 1457619 41854 47819 431637 833723 974775 1024270 1180174 1641880 1669465 896896 1156528']


Session号为14160166的用户：
    可能点击的商品序列为：['1792575 687129 274754 666755 312131 997205 689529 274821 1438482 20012 1129217 1029069 114147 1036074 1196308 877295 1416207 557774 173962 260332']
    可能购买的商品序列为：['1792575 687129 274754 666755 312131 997205 689529 1029069 274821 1438482 114147 1202673 1540345 20012 1129217 54235']


Session号为13064076的用户：
    可能点击的商品序列为：['1685214 1531805 1798916 1208112 620813 1833893 890995 792540 82493 1354951 8557 744282 1854208 979022 1045144 16121 372662 995877 1424250 852331']
    可能购买的商品序列为：['1685214 1531805 1798916 1208112 620813 1833893 82493 890995 792540 979022 1854208 1354951 8557 16121 744282 1045144']


Session号为12931542的用户：
    可能点击的商品序列为：['1833983 1197632 1796103 226413 620545 1492411 993265 105909 674590 1019736 199409 102345 1197226 1134297 1098846 582014 202774 356057 1680387 147205']
    可能购买的商品序列为：['1833983 1197632 1796103 226413 1492411 620545 993265 105909 1019736 674590 199409 1197226 202774 102345 1134297 1098846']


Session号为13697432的用户：
    可能点击的商品序列为：['1296980 1013091 292791 1632953 1599316 1409901 425031 1371621 709635 1417314 1433517 1230612 1222084 482238 144455 1152559 1818902 1491350 1663055 409538']
    可能购买的商品序列为：['1296980 1013091 292791 1632953 1599316 1230612 425031 1409901 709635 1417314 1433517 31743 1491350 250297 1150001 1830282 144455 1069228 1152559 1663055']


Session号为13102811的用户：
    可能点击的商品序列为：['221749 1595183 212264 1370557 885193 512326 542960 1237688 1656362 1450473 424881 375907 1133136 1379497 1788750 112746 821493 1804441 1673149 1011164']
    可能购买的商品序列为：['221749 1595183 212264 433413 885193 1178678 1656362 1133136 1237688 542960 656607 161567 235110 326029 505541 600876 708894 909397 925067 1166590']


Session号为14560351的用户：
    可能点击的商品序列为：['954118 1510044 274967 456331 823143 66284 1171965 1389380 1775115 389023 1030028 76103 83484 114330 224409 303476 432473 481515 513978 577724']
    可能购买的商品序列为：['954118 1510044 274967 456331 66284 389023 312585 823143 1171965 1389380 1775115 772240 1030028 76103 83484 114330 152149 224409 300059 303476']


Session号为14119775的用户：
    可能点击的商品序列为：['1420240 208189 7793 1007548 897199 1566944 881646 507852 1260870 407533 1494678 1572293 1188611 87613 807747 108125 1700227 831165 901830 126784']
    可能购买的商品序列为：['1420240 208189 507852 7793 897199 1494678 1007548 407533 1566944 881646 1260870 1572293 126784 1188611 87613 807747']